### ISSUE TITLE
Chaining calculations

### ISSUE THREAD

**Issue by maxigaz** [maxigaz/js-calculator#5]
# Examples to test

- [x] `6 + 6 +`
- [x] `6 + 6 = +` (same as above, but the equal sign is pressed as well)

# Tasks
- [X] ~~When pressing `+` for the second time, show subresult on screen, store it in cache and wait for new inputNum (reset screen on typing first digit)~~ That's what `calculate` does already.
- [x] Let the program know when to calculate by pressing an operator for the second time:
   - `cache` and `inputNum` variables empty?
   - ~~new boolean variable as switch?~~
- [x] Solve the discrepancy between the type of `result` and `cache` (array of chars vs number)

**Comment by maxigaz** [comment]
Finally working in the latest version.
